# Generated by Django 3.1.3 on 2020-12-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
                ('info_data', models.TextField()),
                ('wish', models.CharField(choices=[('V', 'visited'), ('W', 'wish'), ('N', 'not yet')], default='N', max_length=1)),
            ],
        ),
    ]
