# Generated by Django 3.1.3 on 2020-12-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='tittle',
            new_name='title',
        ),
    ]
