# Generated by Django 3.1.3 on 2020-12-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_information_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='time',
            field=models.DateField(default=''),
        ),
    ]
