# Generated by Django 3.1.3 on 2020-12-16 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_information_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='time',
            field=models.DateField(default=datetime.datetime(2020, 12, 16, 17, 30, 42, 144559, tzinfo=utc)),
        ),
    ]
