# Generated by Django 3.1.3 on 2020-12-16 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_auto_20201217_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='time',
        ),
    ]
