# Generated by Django 3.1.3 on 2020-12-16 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0009_auto_20201217_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='place',
        ),
        migrations.RemoveField(
            model_name='information',
            name='timedate',
        ),
    ]
